stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: reggl.nekosunevr.co.uk/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  DOCKER_TAG: "$CI_COMMIT_REF_SLUG"
  LATEST_TAG: "main"

before_script:
  - echo "Using host Docker daemon..."
  - docker info || echo "Failed to connect to Docker daemon"

build:
  stage: build
  image: docker:24.0.0
  tags:
    - docker-runners 
  script:
    - echo "Checking if image exists..."
    - |
      if docker manifest inspect $DOCKER_IMAGE:$DOCKER_TAG > /dev/null 2>&1; then
        echo "Image already exists, skipping build."
      else
        echo "Building Docker image..."
        docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
        docker tag $DOCKER_IMAGE:$DOCKER_TAG $DOCKER_IMAGE:$LATEST_TAG
      fi
    - docker images

deploy:
  stage: deploy
  image: docker:24.0.0
  tags:
    - docker-runners
  script:
    - echo "Deploying Docker image to GitLab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin https://reggl.nekosunevr.co.uk
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
    - docker push $DOCKER_IMAGE:$LATEST_TAG
  only:
    - main
